// Generated by CoffeeScript 1.6.2
(function() {
  jQuery(function($) {
    var env, manager;

    env = {
      gamediv: $('#gameDiv'),
      description: {}
    };
    manager = new GameManager(env);
    window.Manager = manager;
  });

}).call(this);
