// Generated by CoffeeScript 1.6.2
(function() {
  var globals, mfs;

  globals = {
    '../vendor/underscore/underscore.js': '_'
  };

  window.require = function(path, herp) {
    var ext, name, _ref, _ref1;

    if ((herp != null)) {
      path = herp;
    }
    if (path in globals) {
      return window[globals[path]];
    }
    _ref = BrowserFS.node.path.basename(path).split('.'), name = _ref[0], ext = _ref[1];
    return (_ref1 = window[name]) != null ? _ref1 : window[name] = {};
  };

  BrowserFS.install(window);

  mfs = new BrowserFS.FileSystem.MountableFileSystem();

  mfs.mount('/tmp', new BrowserFS.FileSystem.InMemory());

  mfs.mount('/sys', new BrowserFS.FileSystem.XmlHttpRequest('/listings.json', 'doppio-jvm'));

  BrowserFS.initialize(mfs);

  window.node = BrowserFS.node;

  node.fs.mkdirSync('/tmp');

  node.process.chdir('/tmp');

}).call(this);
